import Head from 'next/head' 
import NavigationBar from '../components/Navbar/Navigationbar'
import Footer from '../components/Footer/footer'
import Banner from '../components/Banner/Banner' 
import Launched from '../components/Launched_projects/launched'
import PopNew from '../components/Popular&new_projects/pop&new' 

export default function Home() {
  return (
    <div>
      <Head>
        <title>SparkLaunched</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
      <NavigationBar/>

      <main className=' pt-[4rem]'>
        <Banner/>
        <Launched/>
        <PopNew/> 
      </main>

      <footer className="">
      <Footer/>
  
      
      </footer>
    </div>
  )
}
